FROM node:24-alpine AS builder
WORKDIR /app/shepherd_client

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build



FROM nginx:1-alpine AS runner

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/shepherd_client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
