[package]
name = "infra-auth"
version.workspace = true
edition.workspace = true

[dependencies]
argon2.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
futures-util.workspace = true
jsonwebtoken.workspace = true
moka.workspace = true
rand.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
utoipa.workspace = true
validator.workspace = true
uuid.workspace = true
infra-kernel = { workspace = true, features = ["debugging"] }
infra-postgres.workspace = true
infra-redis.workspace = true

[lints]
workspace = true
