[workspace]
resolver = "2"
members = [
    "infra/kernel",
    "infra/ntree",
    "infra/auth",
    "infra/authz",
    "infra/postgres",
    "infra/redis",
    "infra/host",
    "infra/app-sdk",
    "infra/jobs",
    "infra/worker",
    "applications/hrm",
    "runtime",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["PhuongDoVan <vampirephuong@gmail.com>"]

[workspace.dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
tokio = { version = "*", features = ["full"] }
tokio-macros = { version = "*" }
tokio-util = { version = "*", features = ["rt"] }
futures-util = { version = "*" }
async-trait = { version = "*" }
axum = { version = "*", features = ["multipart"] }
tower = { version = "*" }
tower-http = { version = "*", features = ["cors", "timeout", "trace"] }
jsonwebtoken = { version = "*", features = ["rust_crypto"] }
casbin = { version = "*", default-features = false, features = ["incremental", "cached", "runtime-tokio"] }
sqlx-adapter = { version = "*", default-features = false, features = ["postgres", "runtime-tokio-rustls"] }
ed25519-dalek = { version = "*", features = ["rand_core"] }
rand = { version = "*" }
uuid = { version = "*", features = ["v4", "serde"] }
argon2 = { version = "*" }
passphrase-hash = { version = "*" }
validator = { version = "*", features = ["derive"] }
tracing = { version = "*" }
tracing-subscriber = { version = "*", features = ["env-filter", "fmt", "registry"] }
sqlx = { version = "*", default-features = false, features = ["runtime-tokio", "postgres", "tls-rustls", "macros", "chrono", "uuid"] }
dotenvy = { version = "*" }
parking_lot = { version = "*" }
base64 = { version = "*" }
sha2 = { version = "*" }
cfg-if = { version = "*" }
thiserror = { version = "*" }
governor = { version = "*", features = ["std", "dashmap"] }
tower_governor = { version = "*", features = ["axum"] }
dashmap = { version = "*" }
moka = { version = "*", features = ["future"] }
redis = { version = "*", features = ["tokio-comp", "connection-manager"] }
arc-swap = { version = "*" }
chrono = { version = "*", features = ["serde"] }
time = { version = "*", features = ["parsing", "macros"] }
utoipa = { version = "*", features = ["axum_extras", "chrono", "uuid"] }
calamine = { version = "*" }
rust_xlsxwriter = { version = "*" }
# reusable infra crates
infra-kernel = { path = "infra/kernel" }
infra-ntree = { path = "infra/ntree" }
infra-auth = { path = "infra/auth" }
infra-authz = { path = "infra/authz" }
infra-postgres = { path = "infra/postgres" }
infra-redis = { path = "infra/redis" }
infra-host = { path = "infra/host" }
infra-app-sdk = { path = "infra/app-sdk" }
infra-jobs = { path = "infra/jobs" }
infra-worker = { path = "infra/worker" }
# installed applications
app-hrm = { path = "applications/hrm" }

[workspace.lints.clippy]
unwrap_used = "deny"
indexing_slicing = "deny"


[workspace.lints.rust]
unsafe_code = "forbid"
