FROM rust:1-slim-bookworm AS base
WORKDIR /app/shepherd_server

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


FROM base AS builder

RUN rustup component add clippy

COPY . .
ENV SQLX_OFFLINE=true
RUN cargo clippy --all --workspace \
    && cargo build --release -p shepherd-runtime \
        --bin shepherd-srv \
        --bin shepherd-tenant-bootstrap


FROM debian:bookworm-slim AS runner
WORKDIR /app

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/shepherd_server/target/linux-amd64/release/shepherd-srv /app/shepherd-srv
COPY --from=builder /app/shepherd_server/target/linux-amd64/release/shepherd-tenant-bootstrap /app/shepherd-tenant-bootstrap

EXPOSE 8000
CMD ["/app/shepherd-srv"]
