[package]
name = "shepherd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "shepherd-dev-db-seeding"
path = "src/bin/dev_db_seeding.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
tokio-util.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
jsonwebtoken.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
parking_lot.workspace = true
cfg-if.workspace = true
sqlx.workspace = true
dotenvy.workspace = true
time.workspace = true
thiserror.workspace = true
ts-rs.workspace = true
uuid.workspace = true
calamine.workspace = true
rust_xlsxwriter.workspace = true
infra-app-sdk.workspace = true
infra-kernel = { workspace = true, features = ["debugging"] }
infra-auth = { path = "../../infra/auth", default-features = false, features = ["keycloak"] }
infra-authz.workspace = true
infra-host.workspace = true
infra-postgres.workspace = true
infra-notifier.workspace = true

[lints]
workspace = true
