// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPermissionOverrideContract } from "./AccountPermissionOverrideContract";
import type { AccountRoleAssignmentContract } from "./AccountRoleAssignmentContract";
import type { AccountStatus } from "./AccountStatus";
import type { RoleCode } from "./RoleCode";

export type AccessControlUser = { account_id: string, username: string, email: string | null, status: AccountStatus, primary_role: RoleCode, authorization_version: bigint, assignments: Array<AccountRoleAssignmentContract>, permission_overrides: Array<AccountPermissionOverrideContract>, };
