// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRoleScope } from "./AccessRoleScope";
import type { PermissionCode } from "./PermissionCode";
import type { RoleCode } from "./RoleCode";

export type AccessControlRole = { code: RoleCode, display_name: string, description: string | null, scope: AccessRoleScope, is_system: boolean, is_active: boolean, version: bigint, permission_codes: Array<PermissionCode>, assigned_account_count: bigint, };
