// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessControlAuditEntry } from "./AccessControlAuditEntry";
import type { AccessControlBranch } from "./AccessControlBranch";
import type { AccessControlPermission } from "./AccessControlPermission";
import type { AccessControlRole } from "./AccessControlRole";
import type { AccessControlUser } from "./AccessControlUser";

export type AccessControlSnapshot = { branches: Array<AccessControlBranch>, permissions: Array<AccessControlPermission>, roles: Array<AccessControlRole>, users: Array<AccessControlUser>, audit: Array<AccessControlAuditEntry>, };
