// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionCode } from "./PermissionCode";

export type AccessControlPermission = { code: PermissionCode, description: string, };
