// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionCode } from "./PermissionCode";
import type { PermissionOverrideEffect } from "./PermissionOverrideEffect";

export type AccountPermissionOverrideContract = { permission_code: PermissionCode, branch_id: string | null, effect: PermissionOverrideEffect, expires_at: string | null, };
