// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthUserSummary = { auth_user_id: string, account_id: string, username: string, email: string | null, primary_role: string, account_status: string, provider_status: string, email_confirmed: boolean, created_at: string | null, last_sign_in_at: string | null, };
