// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRoleScope } from "./AccessRoleScope";
import type { PermissionCode } from "./PermissionCode";
import type { RoleCode } from "./RoleCode";

export type CreateAccessControlRoleRequest = { code: RoleCode, display_name: string, description: string | null, scope: AccessRoleScope, permission_codes: Array<PermissionCode>, };
