// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAccessControlBranchRequest = { code: string, name: string, time_zone: string, };
