// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentUserProfile = { tenant_id: string, account_id: string, username: string, email: string | null, primary_role: string, roles: Array<string>, permissions: Array<string>, };
