// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleCode } from "./RoleCode";

export type TenantMembershipSummary = { tenant_id: string, account_id: string, tenant_slug: string, tenant_display_name: string, username: string, email: string | null, primary_role: RoleCode, };
