// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionCode } from "./PermissionCode";

export type UpdateAccessControlRoleRequest = { display_name: string, description: string | null, is_active: boolean, expected_version: bigint, permission_codes: Array<PermissionCode>, };
