// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAccessControlBranchRequest = { name: string, time_zone: string, status: string, expected_version: bigint, };
