// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessControlRole } from "./AccessControlRole";

export type AccessControlRolePage = { items: Array<AccessControlRole>, next_cursor: string | null, has_more: boolean, limit: number, };
