// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccessControlBranch = { id: string, code: string, name: string, time_zone: string, status: string, version: bigint, };
