// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleCode } from "./RoleCode";

export type AccountRoleAssignmentContract = { role_code: RoleCode, branch_id: string | null, };
