// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthUserSummary } from "./AuthUserSummary";

export type AuthUserPage = { items: Array<AuthUserSummary>, next_cursor: string | null, has_more: boolean, limit: number, };
