// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPermissionOverrideContract } from "./AccountPermissionOverrideContract";
import type { AccountRoleAssignmentContract } from "./AccountRoleAssignmentContract";
import type { RoleCode } from "./RoleCode";

export type UpdateAccountAccessRequest = { primary_role: RoleCode, expected_version: bigint, assignments: Array<AccountRoleAssignmentContract>, permission_overrides: Array<AccountPermissionOverrideContract>, };
