[package]
name = "infra-postgres"
version.workspace = true
edition.workspace = true

# [[bin]]
# name = "infra-dev-db-seeding"
# path = "src/bin/dev_db_seeding.rs"

[dependencies]
tokio.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
# crates of the solution
infra-kernel.workspace = true

[lints]
workspace = true
