[package]
name = "shepherd-runtime"
version.workspace = true
edition.workspace = true

[[bin]]
name = "shepherd-server"
path = "src/bin/main.rs"

[[bin]]
name = "shepherd-typescript"
path = "src/bin/typescript.rs"

[dependencies]
axum.workspace = true
dotenvy.workspace = true
tokio.workspace = true
tracing.workspace = true
infra-kernel = { workspace = true, features = ["debugging"] }
infra-host.workspace = true
infra-worker.workspace = true
shepherd.workspace = true

[lints]
workspace = true
