[package]
name = "shepherd-runtime"
version.workspace = true
edition.workspace = true

[[bin]]
name = "shepherd-server"
path = "src/bin/restful.rs"

[[bin]]
name = "shepherd-openapi"
path = "src/bin/openapi.rs"

[dependencies]
axum.workspace = true
dotenvy.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
utoipa.workspace = true
infra-kernel = { workspace = true, features = ["debugging"] }
infra-auth.workspace = true
infra-host.workspace = true
shepherd.workspace = true

[lints]
workspace = true
